#!  /usr/bin/env perl
# Usage: pareto.pl < sizes.dat > pareto.dat.
# stdin follows the format of `sizes.dat` generated by `do-it.pl`.
# stdout is a file that should be plotted something like:
#  plot 'pareto.gp' using 1:2:7 with points pt variable title (column(-2))

# The pointtype (third, inserted) column is the Unicode character to
# use when drawing the points.

use strict;
use warnings;

# Parse arguments.
my ($xcol, $ycol, @front, @front_30s, %keep) = (0, 1);
for my $arg (@ARGV) {
    if ($arg eq '--keep') {
        for my $kk (qw(crx crx+gzip crx+bzip3 30s+crx+gzip)) {
            $keep{$kk} = [];
        }
    } elsif ($arg =~ /^--keep=(.+)$/) {
        $keep{$1} = [];
    } elsif ($arg =~ /(\d+),(\d+)$/) {
        # Subtract one to convert to zero-based indexing of numerical columns.
        $xcol = $1 - 2;
        $ycol = $2 - 2;
        die "invalid columns $arg" if $xcol < 0 or $xcol > 3 or $ycol < 0 or $ycol > 3;
    } else {
        die "usage: $0 [--keep=<config> ...] [<xcol>,<ycol>]"
    }
}

# Optimization direction: 1 = maximize, -1 = minimize
# Column 2 (index 0) = compression ratio (maximize)
# Column 3 = wall time (minimize)
# Column 4 = CPU time (minimize)
# Column 5 = disk space (minimize)
my @dir = (1, -1, -1, -1);

while (<STDIN>) {
    chomp;
    next unless /\S/;

    # Parse the input line.
    if (not /^"([^"]+)" (.+)$/) {
        warn "bad input line: $_";
        next;
    }
    my $name = $1;
    my @fields = split ' ', $2;

    # Update the Pareto front.
    if ($name =~ /^30s/) {
        @front_30s = update_pareto($name, \@fields, @front_30s);
    } else {
        @front = update_pareto($name, \@fields, @front);
    }

    # Do we keep this entry regardless?
    $keep{$name} = [@fields] if exists $keep{$name};
}

# "Forget" entries that are in the fronts and also %keep.
for my $p (@front, @front_30s) {
    delete $keep{$p->[0]};
}

# Merge the fronts with %keep.
my @merged = (@front, @front_30s);
for my ($name, $vals) (%keep) {
    push @merged, [$name, @$vals];
}

# Sort the merged front by $xcol, then print it.
@merged = sort { ($a->[1+$xcol] <=> $b->[1+$xcol]) * $dir[$xcol] } @merged;
for my $p (@merged) {
    print "# $p->[0]\n";
    print join(' ', @{$p}[1..$#{$p}]);
    print "\n\n\n";
}

sub update_pareto {
    my ($name, $fields_ref, @front) = @_;
    my @fields = @$fields_ref;

    # Check if the new point is dominated by any point in the front.
    for my $p (@front) {
        my @p_fields = @{$p}[1..$#{$p}];
        my $better = 0;
        my $worse = 0;
        for my $i (0 .. $#dir) {
            my $val_new = $fields[$i];
            my $val_old = $p_fields[$i];
            if ($val_old * $dir[$i] > $val_new * $dir[$i]) {
                $better = 1;
            } elsif ($val_old * $dir[$i] < $val_new * $dir[$i]) {
                $worse = 1;
                last;
            }
        }
        return @front if $better && !$worse;
    }

    # Remove points in the front that are dominated by the new point.
    my @new_front;
    for my $p (@front) {
        my @p_fields = @{$p}[1..$#{$p}];
        my $better = 0;
        my $worse = 0;
        for my $i (0 .. $#dir) {
            my $val_new = $fields[$i];
            my $val_old = $p_fields[$i];
            if ($val_new * $dir[$i] > $val_old * $dir[$i]) {
                $better = 1;
            } elsif ($val_new * $dir[$i] < $val_old * $dir[$i]) {
                $worse = 1;
                last;
            }
        }
        push @new_front, $p unless $better && !$worse;
    }

    push @new_front, [$name, @fields];
    return @new_front;
}
